// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zLEE7XWZPFRNuU_EWAV84iMokV62WF4',
    appId: '1:140124232414:web:cc76046d978a16f46f004f',
    messagingSenderId: '140124232414',
    projectId: 'impeccable-home-a9123',
    authDomain: 'impeccable-home-a9123.firebaseapp.com',
    storageBucket: 'impeccable-home-a9123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDa-DXiAfCHOS4iaJkVuJ7RVqHh5g97c',
    appId: '1:140124232414:android:d6bd3a30893d32456f004f',
    messagingSenderId: '140124232414',
    projectId: 'impeccable-home-a9123',
    storageBucket: 'impeccable-home-a9123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2DpMP4wd0OwwlJPEKBJ3Xd5Ac5dy9U4',
    appId: '1:140124232414:ios:e911cfa5d17312fc6f004f',
    messagingSenderId: '140124232414',
    projectId: 'impeccable-home-a9123',
    storageBucket: 'impeccable-home-a9123.appspot.com',
    androidClientId: '140124232414-88fsf9kf424ajn5v0qda696mbke92vst.apps.googleusercontent.com',
    iosClientId: '140124232414-3i7eoernn37vu37i1p15un329dmcnl2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.impeccablehomeHelper',
  );
}