import 'package:impeccablehome_helper/model/booking_model.dart';
import 'package:impeccablehome_helper/model/helper_model.dart';
import 'package:impeccablehome_helper/model/notification_model.dart';
import 'package:impeccablehome_helper/model/review_model.dart';
import 'package:impeccablehome_helper/model/service_model.dart';

final List<ServiceModel> services = [
  ServiceModel(
    serviceId: '1',
    serviceName: 'Clean-up & Laundry',
    serviceDescription: 'Thorough cleaning and laundry services.',
    serviceBasePrice: 50.0,
    imagePath: 'assets/icons/cleanup_icon.png',
    colorfulImagePath: 'assets/images/colorful_cleanup_image.png',
  ),
  ServiceModel(
    serviceId: '2',
    serviceName: 'Plumbing',
    serviceDescription: 'Expert plumbing solutions.',
    serviceBasePrice: 75.0,
    imagePath: 'assets/icons/plumbing_icon.png',
    colorfulImagePath: 'assets/images/colorful_plumbing_image.png',
  ),
  ServiceModel(
    serviceId: '3',
    serviceName: 'Cooking',
    serviceDescription: 'Delicious home-cooked meals.',
    serviceBasePrice: 40.0,
    imagePath: 'assets/icons/cooking_icon.png',
    colorfulImagePath: 'assets/images/colorful_cooking_image.png',
  ),
  ServiceModel(
    serviceId: '4',
    serviceName: 'Electricity',
    serviceDescription: 'Electrical repairs and maintenance.',
    serviceBasePrice: 60.0,
    imagePath: 'assets/icons/electricity_icon.png',
    colorfulImagePath: 'assets/images/colorful_electricity_image.png',
  ),
  ServiceModel(
    serviceId: '5',
    serviceName: 'Gardening',
    serviceDescription: 'Garden care and landscaping.',
    serviceBasePrice: 45.0,
    imagePath: 'assets/icons/gardening_icon.png',
    colorfulImagePath: 'assets/images/colorful_gardening_image.png',
  ),
  ServiceModel(
    serviceId: '6',
    serviceName: 'Grocery Shopping',
    serviceDescription: 'Convenient grocery shopping.',
    serviceBasePrice: 30.0,
    imagePath: 'assets/icons/grocery_shopping_icon.png',
    colorfulImagePath: 'assets/images/colorful_grocery_shopping_image.png',
  ),
];

List<HelperModel> helpers = [
  HelperModel(
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    province: "Ontario",
    serviceType: "Cleaning",
    phoneNumber: "+1234567890",
    helperUid: "helper_001",
    lastLogOutAt: "2024-12-01T10:00:00Z",
    status: "online",
    profilePic: "https://picsum.photos/200",
    createdAt: "2024-01-01T10:00:00Z",
    idCardFront: "https://example.com/john_id_front.jpg",
    idCardBack: "https://example.com/john_id_back.jpg",
    idCardNumber: "123456789",
    houseAddress: "123 Main St",
    emergencyContactName: "Jane Doe",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhoneNumber: "+0987654321",
    emergencyContactAddress: "123 Main St",
    isApproved: "yes",
    ratings: 4.5,
    dateOfBirth: "1991-02-15",
    gender: "female",
  ),
  HelperModel(
    firstName: "Emily",
    lastName: "Clark",
    email: "emily.clark@example.com",
    province: "Quebec",
    serviceType: "Cooking",
    phoneNumber: "+1234567891",
    helperUid: "helper_002",
    lastLogOutAt: "2024-11-30T18:00:00Z",
    status: "offline",
    profilePic: "https://picsum.photos/201",
    createdAt: "2024-02-15T12:00:00Z",
    idCardFront: "https://example.com/emily_id_front.jpg",
    idCardBack: "https://example.com/emily_id_back.jpg",
    idCardNumber: "987654321",
    houseAddress: "456 Elm St",
    emergencyContactName: "Michael Clark",
    emergencyContactRelationship: "Brother",
    emergencyContactPhoneNumber: "+0987654322",
    emergencyContactAddress: "456 Elm St",
    isApproved: "yes",
    ratings: 4.8,
    dateOfBirth: "1999-12-04",
    gender: "male",
  ),
  HelperModel(
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    province: "Alberta",
    serviceType: "Gardening",
    phoneNumber: "+1234567892",
    helperUid: "helper_003",
    lastLogOutAt: "2024-12-01T15:00:00Z",
    status: "online",
    profilePic: "https://picsum.photos/202",
    createdAt: "2024-03-01T14:00:00Z",
    idCardFront: "https://example.com/michael_id_front.jpg",
    idCardBack: "https://example.com/michael_id_back.jpg",
    idCardNumber: "1122334455",
    houseAddress: "789 Pine St",
    emergencyContactName: "Sarah Brown",
    emergencyContactRelationship: "Sister",
    emergencyContactPhoneNumber: "+0987654323",
    emergencyContactAddress: "789 Pine St",
    isApproved: "no",
    ratings: 4.0,
    dateOfBirth: "1996-06-11",
    gender: "male",
  ),
  HelperModel(
    firstName: "Sophia",
    lastName: "Martinez",
    email: "sophia.martinez@example.com",
    province: "British Columbia",
    serviceType: "Childcare",
    phoneNumber: "+1234567893",
    helperUid: "helper_004",
    lastLogOutAt: "2024-12-02T09:00:00Z",
    status: "offline",
    profilePic: "https://picsum.photos/203",
    createdAt: "2024-04-10T09:00:00Z",
    idCardFront: "https://example.com/sophia_id_front.jpg",
    idCardBack: "https://example.com/sophia_id_back.jpg",
    idCardNumber: "6677889900",
    houseAddress: "101 Maple St",
    emergencyContactName: "Carlos Martinez",
    emergencyContactRelationship: "Father",
    emergencyContactPhoneNumber: "+0987654324",
    emergencyContactAddress: "101 Maple St",
    isApproved: "yes",
    ratings: 4.7,
    dateOfBirth: "1992-10-03",
    gender: "female",
  ),
  HelperModel(
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@example.com",
    province: "Manitoba",
    serviceType: "Driving",
    phoneNumber: "+1234567894",
    helperUid: "helper_005",
    lastLogOutAt: "2024-11-29T20:00:00Z",
    status: "online",
    profilePic: "https://picsum.photos/204",
    createdAt: "2024-05-01T15:00:00Z",
    idCardFront: "https://example.com/james_id_front.jpg",
    idCardBack: "https://example.com/james_id_back.jpg",
    idCardNumber: "4455667788",
    houseAddress: "202 Oak St",
    emergencyContactName: "Linda Wilson",
    emergencyContactRelationship: "Mother",
    emergencyContactPhoneNumber: "+0987654325",
    emergencyContactAddress: "202 Oak St",
    isApproved: "notsubmitted",
    ratings: 3.9,
    dateOfBirth: "1985-08-30",
    gender: "male",
  ),
  HelperModel(
    firstName: "Olivia",
    lastName: "Lee",
    email: "olivia.lee@example.com",
    province: "Nova Scotia",
    serviceType: "Housekeeping",
    phoneNumber: "+1234567895",
    helperUid: "helper_006",
    lastLogOutAt: "2024-12-01T22:00:00Z",
    status: "offline",
    profilePic: "https://picsum.photos/205",
    createdAt: "2024-06-01T16:00:00Z",
    idCardFront: "https://example.com/olivia_id_front.jpg",
    idCardBack: "https://example.com/olivia_id_back.jpg",
    idCardNumber: "3344556677",
    houseAddress: "303 Birch St",
    emergencyContactName: "Henry Lee",
    emergencyContactRelationship: "Brother",
    emergencyContactPhoneNumber: "+0987654326",
    emergencyContactAddress: "303 Birch St",
    isApproved: "yes",
    ratings: 4.6,
    dateOfBirth: "1996-09-22",
    gender: "female",
  ),
];
List<BookingModel> bookings = [
  BookingModel(
    bookingNumber: 'B001',
    serviceType: 'Clean-up & Laundry',
    customerUid: 'CUST001',
    customerName: 'John Doe',
    helperUid: 'HELP001',
    helperName: 'Alice Helper',
    workingDay: DateTime(2024, 12, 10),
    startTime: DateTime(2024, 12, 10, 9, 0),
    finishedTime: DateTime(2024, 12, 10, 12, 0),
    location: '123 Main Street',
    note: 'Handle delicate items with care',
    paymentMethod: 'Credit Card',
    cardName: 'John Doe',
    cardNumber: '1234 5678 9876 5432',
    cvv: '123',
    status: '-1', // Scheduled
  ),
  BookingModel(
    bookingNumber: 'B002',
    serviceType: 'Plumbing',
    customerUid: 'CUST002',
    customerName: 'Jane Smith',
    helperUid: 'HELP002',
    helperName: 'Bob Helper',
    workingDay: DateTime(2024, 12, 11),
    startTime: DateTime(2024, 12, 11, 14, 0),
    finishedTime: DateTime(2024, 12, 11, 16, 30),
    location: '456 Elm Avenue',
    note: 'Fix leaking sink',
    paymentMethod: 'Cash',
    cardName: '',
    cardNumber: '',
    cvv: '',
    status: '2', // In progress
  ),
  BookingModel(
    bookingNumber: 'B003',
    serviceType: 'Cooking',
    customerUid: 'CUST003',
    customerName: 'Emily Rose',
    helperUid: 'HELP003',
    helperName: 'Charlie Helper',
    workingDay: DateTime(2024, 12, 12),
    startTime: DateTime(2024, 12, 12, 17, 0),
    finishedTime: DateTime(2024, 12, 12, 18, 30),
    location: '789 Oak Lane',
    note: 'Prepare vegetarian meals',
    paymentMethod: 'Credit Card',
    cardName: 'Emily Rose',
    cardNumber: '9876 5432 1234 5678',
    cvv: '456',
    status: '2', // Completed
  ),
  BookingModel(
    bookingNumber: 'B004',
    serviceType: 'Electricity',
    customerUid: 'CUST004',
    customerName: 'Michael Brown',
    helperUid: 'HELP004',
    helperName: 'Daisy Helper',
    workingDay: DateTime(2024, 12, 13),
    startTime: DateTime(2024, 12, 13, 10, 0),
    finishedTime: DateTime(2024, 12, 13, 12, 30),
    location: '321 Pine Road',
    note: 'Install ceiling fan',
    paymentMethod: 'Debit Card',
    cardName: 'Michael Brown',
    cardNumber: '5678 1234 4321 8765',
    cvv: '789',
    status: '3', // Cancelled
  ),
];



final helper1WorkingTimes = [
  {'day': 'Monday', 'startTime': '09:00', 'finishedTime': '17:00'},
  {'day': 'Tuesday', 'startTime': '10:00', 'finishedTime': '18:00'},
];

final comment1PicandName = {
  'name': 'John Doe',
  'profilePic': "https://picsum.photos/200",
};

final List<ReviewModel> mockReviews = [
    ReviewModel(
      uid: 'user1',
      userName: 'Alice',
      profilePic:
          'https://picsum.photos/200',
      ratings: 4.5,
      reviewContent: 'Great service! Will recommend to others.',
      reviewPics: [
        'https://picsum.photos/208',
        'https://picsum.photos/209',
      ],
    ),
    ReviewModel(
      uid: 'user2',
      userName: 'Bob',
      profilePic:
          'https://picsum.photos/201',
      ratings: 3.0,
      reviewContent: 'Good, but room for improvement.',
      reviewPics: [],
    ),
    ReviewModel(
      uid: 'user3',
      userName: 'Charlie',
      profilePic:
          'https://picsum.photos/202',
      ratings: 5.0,
      reviewContent: 'Amazing experience, very professional!',
      reviewPics: [
        'https://picsum.photos/210',
      ],
    ),
  ];



// Mock data for NotificationModel
List<NotificationModel> mockNotifications = [
  NotificationModel(
    title: 'We will have a scheduled maintenance tomorrow',
    image: 'https://picsum.photos/200',
    createdAt: DateTime.now().subtract(Duration(hours: 2)),
    content: 'We will have a scheduled maintenance tomorrow from 1 AM to 3 AM. We sincerely apologize for this inconvenience',
    type: "serviceUpdate",
    status: "notYetOpened", // Example status
  ),
  NotificationModel(
    title: 'Your booking #12345 has been confirmed',
    image: 'https://picsum.photos/201',
    createdAt: DateTime.now().subtract(Duration(days: 2)),
    content: 'Your booking #12345 has been confirmed.',
    type: "inform",
    bookingNumber: '12345',
    status: "opened", // Example status
  ),
  NotificationModel(
    title: 'Unusual login attempt detected.',
    image: 'https://picsum.photos/202',
    createdAt: DateTime.now().subtract(Duration(minutes: 30)),
    content: 'Unusual login attempt detected. Please verify your account.',
    type: "warning",
    status: "notYetOpened", // Example status
  ),
];
